// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUBzXFdo9SwfCbR7iekYdRQL8a8-PGFhU',
    appId: '1:372441154372:web:0e6eee7b908e01fe380d11',
    messagingSenderId: '372441154372',
    projectId: 'tiktok-3b550',
    authDomain: 'tiktok-3b550.firebaseapp.com',
    storageBucket: 'tiktok-3b550.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4de7itOfrAuJUMYF85sfgmScUx50dFZQ',
    appId: '1:372441154372:android:50367fb47713daaa380d11',
    messagingSenderId: '372441154372',
    projectId: 'tiktok-3b550',
    storageBucket: 'tiktok-3b550.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjZkeGQ_f5BmG5MJ07NjuCg9mASa7iL_o',
    appId: '1:372441154372:ios:6bf6a064e8894b4e380d11',
    messagingSenderId: '372441154372',
    projectId: 'tiktok-3b550',
    storageBucket: 'tiktok-3b550.appspot.com',
    iosClientId: '372441154372-b7cfn8oovque4r3bca5hm2ne6bikrvov.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjZkeGQ_f5BmG5MJ07NjuCg9mASa7iL_o',
    appId: '1:372441154372:ios:6bf6a064e8894b4e380d11',
    messagingSenderId: '372441154372',
    projectId: 'tiktok-3b550',
    storageBucket: 'tiktok-3b550.appspot.com',
    iosClientId: '372441154372-b7cfn8oovque4r3bca5hm2ne6bikrvov.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktok',
  );
}
